#
# This model specification was automatically generated by Onyx
# 
require("OpenMx");
modelData <- read.table(DATAFILENAME, header = TRUE) 
manifests<-c("g1","g2","g3","os1","os2","os3","fs1","fs2","fs3","fs4","fs5")
latents<-c("GOV","SPON","FS","G1","G2","G3","OS1","OS2","OS3","FS1","FS2","FS3","FS4","FS5")
model <- mxModel("FLOSS_Success_032214", 
type="RAM",
manifestVars = manifests,
latentVars = latents,
mxPath(from="GOV",to=c("FS"), free=c(FALSE), value=c(1.0) , arrows=1, label=c("GOV_TO_FS") ),
mxPath(from="SPON",to=c("FS"), free=c(FALSE), value=c(1.0) , arrows=1, label=c("SPON_TO_FS") ),
mxPath(from="G1",to=c("GOV","g1"), free=c(FALSE,FALSE), value=c(1.0,1.0) , arrows=1, label=c("G1_TO_GOV","g1_TO_G1") ),
mxPath(from="G2",to=c("GOV","g2"), free=c(FALSE,FALSE), value=c(1.0,1.0) , arrows=1, label=c("G2_TO_GOV","g2_TO_G2") ),
mxPath(from="G3",to=c("GOV","g3"), free=c(FALSE,FALSE), value=c(1.0,1.0) , arrows=1, label=c("G3_TO_GOV","g3_TO_G3") ),
mxPath(from="OS1",to=c("SPON","os1"), free=c(FALSE,FALSE), value=c(1.0,1.0) , arrows=1, label=c("OS1_TO_SPON","os1_TO_OS1") ),
mxPath(from="OS2",to=c("SPON","os2"), free=c(FALSE,FALSE), value=c(1.0,1.0) , arrows=1, label=c("OS2_TO_SPON","os2_TO_OS2") ),
mxPath(from="OS3",to=c("SPON","os3"), free=c(FALSE,FALSE), value=c(1.0,1.0) , arrows=1, label=c("OS3_TO_SPON","os3_TO_OS3") ),
mxPath(from="FS1",to=c("FS","fs1"), free=c(FALSE,FALSE), value=c(1.0,1.0) , arrows=1, label=c("FS1_TO_FS","fs1_TO_FS1") ),
mxPath(from="FS2",to=c("FS","fs2"), free=c(FALSE,FALSE), value=c(1.0,1.0) , arrows=1, label=c("FS2_TO_FS","fs2_TO_FS2") ),
mxPath(from="FS3",to=c("FS","fs3"), free=c(FALSE,FALSE), value=c(1.0,1.0) , arrows=1, label=c("FS3_TO_FS","fs3_TO_FS3") ),
mxPath(from="FS4",to=c("FS","fs4"), free=c(FALSE,FALSE), value=c(1.0,1.0) , arrows=1, label=c("FS4_TO_FS","fs4_TO_FS4") ),
mxPath(from="FS5",to=c("FS","fs5"), free=c(FALSE,FALSE), value=c(1.0,1.0) , arrows=1, label=c("FS5_TO_FS","fs5_TO_FS5") ),
mxPath(from="GOV",to=c("GOV"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_GOV") ),
mxPath(from="SPON",to=c("SPON"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_SPON") ),
mxPath(from="FS",to=c("FS"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FS") ),
mxPath(from="G1",to=c("G1"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_G1") ),
mxPath(from="G2",to=c("G2"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_G2") ),
mxPath(from="G3",to=c("G3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_G3") ),
mxPath(from="OS1",to=c("OS1"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OS1") ),
mxPath(from="OS2",to=c("OS2"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OS2") ),
mxPath(from="OS3",to=c("OS3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OS3") ),
mxPath(from="FS1",to=c("FS1"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FS1") ),
mxPath(from="FS2",to=c("FS2"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FS2") ),
mxPath(from="FS3",to=c("FS3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FS3") ),
mxPath(from="FS4",to=c("FS4"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FS4") ),
mxPath(from="FS5",to=c("FS5"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FS5") ),
mxPath(from="g1",to=c("g1"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_g1") ),
mxPath(from="g2",to=c("g2"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_g2") ),
mxPath(from="g3",to=c("g3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_g3") ),
mxPath(from="os1",to=c("os1"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_os1") ),
mxPath(from="os2",to=c("os2"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_os2") ),
mxPath(from="os3",to=c("os3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_os3") ),
mxPath(from="fs1",to=c("fs1"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_fs1") ),
mxPath(from="fs2",to=c("fs2"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_fs2") ),
mxPath(from="fs3",to=c("fs3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_fs3") ),
mxPath(from="fs4",to=c("fs4"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_fs4") ),
mxPath(from="fs5",to=c("fs5"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_fs5") ),
mxPath(from="one",to=c("g1","g2","g3","os1","os2","os3","fs1","fs2","fs3","fs4","fs5"), free=F, value=0, arrows=1),
mxData(modelData, type = "raw")
);

result <- mxRun(model)
summary(result)
