#
# This model specification was automatically generated by Onyx
#
library(lavaan);
modelData <- read.table(DATAFILENAME, header = TRUE) ;
 model<-"
! regressions 
   G1=~1.0*g1
   G2=~1.0*g2
   G3=~1.0*g3
   OS1=~1.0*os1
   OS2=~1.0*os2
   OS3=~1.0*os3
   FS1=~1.0*fs1
   FS2=~1.0*fs2
   FS3=~1.0*fs3
   FS4=~1.0*fs4
   FS5=~1.0*fs5
   G1=~1.0*GOV
   G2=~1.0*GOV
   G3=~1.0*GOV
   OS1=~1.0*SPON
   OS2=~1.0*SPON
   OS3=~1.0*SPON
   GOV=~1.0*FS
   SPON=~1.0*FS
   FS1=~1.0*FS
   FS2=~1.0*FS
   FS3=~1.0*FS
   FS4=~1.0*FS
   FS5=~1.0*FS
! residuals, variances and covariances
   GOV ~~ VAR_GOV*GOV
   SPON ~~ VAR_SPON*SPON
   FS ~~ VAR_FS*FS
   G1 ~~ VAR_G1*G1
   G2 ~~ VAR_G2*G2
   G3 ~~ VAR_G3*G3
   OS1 ~~ VAR_OS1*OS1
   OS2 ~~ VAR_OS2*OS2
   OS3 ~~ VAR_OS3*OS3
   FS1 ~~ VAR_FS1*FS1
   FS2 ~~ VAR_FS2*FS2
   FS3 ~~ VAR_FS3*FS3
   FS4 ~~ VAR_FS4*FS4
   FS5 ~~ VAR_FS5*FS5
   g1 ~~ VAR_g1*g1
   g2 ~~ VAR_g2*g2
   g3 ~~ VAR_g3*g3
   os1 ~~ VAR_os1*os1
   os2 ~~ VAR_os2*os2
   os3 ~~ VAR_os3*os3
   fs1 ~~ VAR_fs1*fs1
   fs2 ~~ VAR_fs2*fs2
   fs3 ~~ VAR_fs3*fs3
   fs4 ~~ VAR_fs4*fs4
   fs5 ~~ VAR_fs5*fs5
   GOV ~~ 0.0*SPON
   GOV ~~ 0.0*OS1
   GOV ~~ 0.0*OS2
   GOV ~~ 0.0*OS3
   GOV ~~ 0.0*FS1
   GOV ~~ 0.0*FS2
   GOV ~~ 0.0*FS3
   GOV ~~ 0.0*FS4
   GOV ~~ 0.0*FS5
   SPON ~~ 0.0*G1
   SPON ~~ 0.0*G2
   SPON ~~ 0.0*G3
   SPON ~~ 0.0*FS1
   SPON ~~ 0.0*FS2
   SPON ~~ 0.0*FS3
   SPON ~~ 0.0*FS4
   SPON ~~ 0.0*FS5
   FS ~~ 0.0*G1
   FS ~~ 0.0*G2
   FS ~~ 0.0*G3
   FS ~~ 0.0*OS1
   FS ~~ 0.0*OS2
   FS ~~ 0.0*OS3
   G1 ~~ 0.0*G2
   G1 ~~ 0.0*G3
   G1 ~~ 0.0*OS1
   G1 ~~ 0.0*OS2
   G1 ~~ 0.0*OS3
   G1 ~~ 0.0*FS1
   G1 ~~ 0.0*FS2
   G1 ~~ 0.0*FS3
   G1 ~~ 0.0*FS4
   G1 ~~ 0.0*FS5
   G2 ~~ 0.0*G3
   G2 ~~ 0.0*OS1
   G2 ~~ 0.0*OS2
   G2 ~~ 0.0*OS3
   G2 ~~ 0.0*FS1
   G2 ~~ 0.0*FS2
   G2 ~~ 0.0*FS3
   G2 ~~ 0.0*FS4
   G2 ~~ 0.0*FS5
   G3 ~~ 0.0*OS1
   G3 ~~ 0.0*OS2
   G3 ~~ 0.0*OS3
   G3 ~~ 0.0*FS1
   G3 ~~ 0.0*FS2
   G3 ~~ 0.0*FS3
   G3 ~~ 0.0*FS4
   G3 ~~ 0.0*FS5
   OS1 ~~ 0.0*OS2
   OS1 ~~ 0.0*OS3
   OS1 ~~ 0.0*FS1
   OS1 ~~ 0.0*FS2
   OS1 ~~ 0.0*FS3
   OS1 ~~ 0.0*FS4
   OS1 ~~ 0.0*FS5
   OS2 ~~ 0.0*OS3
   OS2 ~~ 0.0*FS1
   OS2 ~~ 0.0*FS2
   OS2 ~~ 0.0*FS3
   OS2 ~~ 0.0*FS4
   OS2 ~~ 0.0*FS5
   OS3 ~~ 0.0*FS1
   OS3 ~~ 0.0*FS2
   OS3 ~~ 0.0*FS3
   OS3 ~~ 0.0*FS4
   OS3 ~~ 0.0*FS5
   FS1 ~~ 0.0*FS2
   FS1 ~~ 0.0*FS3
   FS1 ~~ 0.0*FS4
   FS1 ~~ 0.0*FS5
   FS2 ~~ 0.0*FS3
   FS2 ~~ 0.0*FS4
   FS2 ~~ 0.0*FS5
   FS3 ~~ 0.0*FS4
   FS3 ~~ 0.0*FS5
   FS4 ~~ 0.0*FS5
";
result<-lavaan(model, data=modelData, fixed.x=FALSE, missing="FIML");
summary(result, fit.measures=TRUE);
