#
# This model specification was automatically generated by Onyx
# 
require("OpenMx");
modelData <- read.table(DATAFILENAME, header = TRUE) 
manifests<-c("osi_comp","restrict","vol_contrib")
latents<-c("GOV")
allVariables <- c("GOV","osi_comp","restrict","vol_contrib")
model <- mxModel("FLOSS_GOV_073014", 
type="RAM",
mxMatrix("Full", nrow=4,ncol=4,values=c(
0.0,0.0,0.0,0.0,
1.0,0.0,0.0,0.0,
1.0,0.0,0.0,0.0,
1.0,0.0,0.0,0.0
), free=c(
F,F,F,F,
F,F,F,F,
F,F,F,F,
F,F,F,F
),labels=c(
NA,NA,NA,NA,
NA,NA,NA,NA,
NA,NA,NA,NA,
NA,NA,NA,NA
), byrow=TRUE, name="A"),
mxMatrix("Full", nrow=4,ncol=4,values=c(
1.0,0.0,0.0,0.0,
0.0,1.0,0.0,0.0,
0.0,0.0,1.0,0.0,
0.0,0.0,0.0,1.0
), free=c(
T,F,F,F,
F,T,F,F,
F,F,T,F,
F,F,F,T
),labels=c(
"VAR_GOV",NA,NA,NA,
NA,"VAR_g1",NA,NA,
NA,NA,"VAR_g2",NA,
NA,NA,NA,"VAR_g3"
), byrow=TRUE, name="S"),
mxMatrix("Full", nrow=3,ncol=4,dimnames=list(manifests,allVariables), values=c(
0.0,1.0,0.0,0.0,
0.0,0.0,1.0,0.0,
0.0,0.0,0.0,1.0
), free=c(
F,F,F,F,
F,F,F,F,
F,F,F,F
),labels=c(
NA,NA,NA,NA,
NA,NA,NA,NA,
NA,NA,NA,NA
), byrow=TRUE, name="F"),
mxMatrix("Full", nrow=1,ncol=4,dimnames=list(NULL,allVariables), values=c(
0.0,0.0,0.0,0.0
), free=c(
F,F,F,F
),labels=c(
NA,NA,NA,NA
), byrow=TRUE, name="M"),
mxData(modelData, type = "raw"),
mxRAMObjective("A","S","F","M")
)

result <- mxRun(model)
summary(result)
