#
# This model specification was automatically generated by Onyx
#
library(lavaan);
modelData <- read.table(DATAFILENAME, header = TRUE) ;
 model<-"
! regressions 
   GOV=~1.0*osi_comp
   GOV=~1.0*restrict
   GOV=~1.0*vol_contrib
! residuals, variances and covariances
   GOV ~~ VAR_GOV*GOV
   osi_comp ~~ VAR_g1*osi_comp
   restrict ~~ VAR_g2*restrict
   vol_contrib ~~ VAR_g3*vol_contrib
";
result<-lavaan(model, data=modelData, fixed.x=FALSE, missing="FIML");
summary(result, fit.measures=TRUE);
