#
# This model specification was automatically generated by Onyx
# 
require("OpenMx");
modelData <- read.table(DATAFILENAME, header = TRUE) 
manifests<-c("osi_comp","restrict","vol_contrib")
latents<-c("GOV")
model <- mxModel("FLOSS_GOV_073014", 
type="RAM",
manifestVars = manifests,
latentVars = latents,
mxPath(from="GOV",to=c("osi_comp","restrict","vol_contrib"), free=c(FALSE,FALSE,FALSE), value=c(1.0,1.0,1.0) , arrows=1, label=c("GOV__osi_comp","GOV__restrict","GOV__vol_contrib") ),
mxPath(from="GOV",to=c("GOV"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_GOV") ),
mxPath(from="osi_comp",to=c("osi_comp"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_g1") ),
mxPath(from="restrict",to=c("restrict"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_g2") ),
mxPath(from="vol_contrib",to=c("vol_contrib"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_g3") ),
mxPath(from="one",to=c("osi_comp","restrict","vol_contrib"), free=F, value=0, arrows=1),
mxData(modelData, type = "raw")
);

result <- mxRun(model)
summary(result)
