#
# This model specification was automatically generated by Onyx
# 
require("sem");
modelData <- read.table(DATAFILENAME, header = TRUE)
paths <- c("GOV <-> GOV", "osi_comp <-> osi_comp", "restrict <-> restrict", "vol_contrib <-> vol_contrib", "GOV -> osi_comp", "GOV -> restrict", "GOV -> vol_contrib")
parameter <- c("VAR_GOV", "VAR_g1", "VAR_g2", "VAR_g3", NA, NA, NA)
values <- c("1.0", "1.0", "1.0", "1.0", "1.0", "1.0", "1.0")
model <- array(c(paths, parameter, values), dim = c(7,3))
colnames(model) <- c("col1","col2","col3")
result <- sem(model = model, data = modelData)
summary(result)
