#
# This model specification was automatically generated by Onyx
# 
require("OpenMx");
modelData <- read.table(DATAFILENAME, header = TRUE) 
manifests<-c()
latents<-c("x1","x1_","x1_")
model <- mxModel("SEM_FLOSS_Test_1", 
type="RAM",
manifestVars = manifests,
latentVars = latents,
mxPath(from="x1",to=c("x1_"), free=c(FALSE), value=c(1.0) , arrows=1, label=c("x1_TO_x1_") ),
mxPath(from="x1_",to=c("x1_"), free=c(FALSE), value=c(1.0) , arrows=1, label=c("x1__TO_x1_") ),
mxPath(from="x1",to=c("x1"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_x1") ),
mxData(modelData, type = "raw")
);

result <- mxRun(model)
summary(result)
