#
# This model specification was automatically generated by Onyx
# 
require("OpenMx");
modelData <- read.table(DATAFILENAME, header = TRUE) 
manifests<-c()
latents<-c("x1","x1_","x1_")
allVariables <- c("x1","x1_","x1_")
model <- mxModel("SEM_FLOSS_Test_1", 
type="RAM",
mxMatrix("Full", nrow=3,ncol=3,values=c(
0.0,0.0,0.0,
0.0,0.0,0.0,
1.0,1.0,0.0
), free=c(
F,F,F,
F,F,F,
F,F,F
),labels=c(
NA,NA,NA,
NA,NA,NA,
NA,NA,NA
), byrow=TRUE, name="A"),
mxMatrix("Full", nrow=3,ncol=3,values=c(
1.0,0.0,0.0,
0.0,0.0,0.0,
0.0,0.0,0.0
), free=c(
T,F,F,
F,F,F,
F,F,F
),labels=c(
"VAR_x1",NA,NA,
NA,NA,NA,
NA,NA,NA
), byrow=TRUE, name="S"),
mxMatrix(name="+name+"),
mxMatrix("Full", nrow=1,ncol=3,dimnames=list(NULL,allVariables), values=c(
0.0,0.0,0.0
), free=c(
F,F,F
),labels=c(
NA,NA,NA
), byrow=TRUE, name="M"),
mxData(modelData, type = "raw"),
mxRAMObjective("A","S","F","M")
)

result <- mxRun(model)
summary(result)
